version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "9001:9001" 
    depends_on:
      - backend
